name: Test
on:
  push:
    branches-ignore:
      - gh-pages
      - releases/**
  pull_request:
    branches-ignore:
      - gh-pages
      - releases/**
    types:
      - opened
      - synchronize
      - reopened
env:
  CI: true
  TZ: Asia/Tokyo
  CHROME_BIN: /usr/bin/google-chrome

jobs:
  test:
    name: "Test on Node.js ${{ matrix.node }} OS: ${{matrix.os}}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    steps:
      - name: Setup google chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: chrome --version
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest
      - run: firefox --version
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Flow Types
        run: yarn flow
      - name: TS Types
        run: yarn test:types
      - name: Test Coverage
        run: yarn test:cover
      - name: Setup for firefox
        run: export DISPLAY=:0
      - name: Unit tests
        run: yarn test:unit:ci
      - name: E2E Tests
        run: yarn test:e2e
